import { TuningPreset } from '../types/tuner';

export const NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];
export const NOTE_NAMES_JA = ['ド', 'ド#', 'レ', 'レ#', 'ミ', 'ファ', 'ファ#', 'ソ', 'ソ#', 'ラ', 'ラ#', 'シ'];

export const TUNING_PRESETS: TuningPreset[] = [
  {
    id: 'high-g',
    name: 'スタンダード (High-G)',
    subName: 'G4 - C4 - E4 - A4',
    description: '最も一般的なウクレレのチューニング。コロコロとしたウクレレらしい軽快なサウンド。',
    strings: [
      {
        stringNumber: 4,
        name: 'G',
        solfege: 'ソ',
        octave: 4,
        frequency: 392.00,
        label: '4弦 (G4)',
        position: 'top-left',
      },
      {
        stringNumber: 3,
        name: 'C',
        solfege: 'ド',
        octave: 4,
        frequency: 261.63,
        label: '3弦 (C4)',
        position: 'bottom-left',
      },
      {
        stringNumber: 2,
        name: 'E',
        solfege: 'ミ',
        octave: 4,
        frequency: 329.63,
        label: '2弦 (E4)',
        position: 'bottom-right',
      },
      {
        stringNumber: 1,
        name: 'A',
        solfege: 'ラ',
        octave: 4,
        frequency: 440.00,
        label: '1弦 (A4)',
        position: 'top-right',
      },
    ],
  },
  {
    id: 'low-g',
    name: 'Low-G (ロージー)',
    subName: 'G3 - C4 - E4 - A4',
    description: '4弦を1オクターブ低く張ったチューニング。ソロ弾きや豊かな低音域を出したい時に最適。',
    strings: [
      {
        stringNumber: 4,
        name: 'G',
        solfege: 'ソ',
        octave: 3,
        frequency: 196.00,
        label: '4弦 (G3)',
        position: 'top-left',
      },
      {
        stringNumber: 3,
        name: 'C',
        solfege: 'ド',
        octave: 4,
        frequency: 261.63,
        label: '3弦 (C4)',
        position: 'bottom-left',
      },
      {
        stringNumber: 2,
        name: 'E',
        solfege: 'ミ',
        octave: 4,
        frequency: 329.63,
        label: '2弦 (E4)',
        position: 'bottom-right',
      },
      {
        stringNumber: 1,
        name: 'A',
        solfege: 'ラ',
        octave: 4,
        frequency: 440.00,
        label: '1弦 (A4)',
        position: 'top-right',
      },
    ],
  },
  {
    id: 'baritone',
    name: 'バリトン (Baritone)',
    subName: 'D3 - G3 - B3 - E4',
    description: 'バリトンウクレレ用（ギターの1〜4弦と同じ音階）。深みのあるアコースティックな音色。',
    strings: [
      {
        stringNumber: 4,
        name: 'D',
        solfege: 'レ',
        octave: 3,
        frequency: 146.83,
        label: '4弦 (D3)',
        position: 'top-left',
      },
      {
        stringNumber: 3,
        name: 'G',
        solfege: 'ソ',
        octave: 3,
        frequency: 196.00,
        label: '3弦 (G3)',
        position: 'bottom-left',
      },
      {
        stringNumber: 2,
        name: 'B',
        solfege: 'シ',
        octave: 3,
        frequency: 246.94,
        label: '2弦 (B3)',
        position: 'bottom-right',
      },
      {
        stringNumber: 1,
        name: 'E',
        solfege: 'ミ',
        octave: 4,
        frequency: 329.63,
        label: '1弦 (E4)',
        position: 'top-right',
      },
    ],
  },
];
